---
title: 'Goals and Tasks'
author: "ASP Boost Team"
date: "30 April 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file is for goal setting and tracking and technical discussion.

## Tasks until ~ 11 May

* simple boost function for scale (estimate var(yi))
* read Wickham "R-Packages"
* try implementing function-testing
* get used to roxygen2






## Tasks to achieve till next Q&A session 04 May 2020 
### (as set in the last meeting)

* L ~~README~~ . 
* S ~~Rmd file for communication~~  (this file)
* JLS ~~Push a boost function~~ 

Initials indicate whom belongs which task. 

Discussion could look like this (The html file is intended to visualize LaTeX):

## Estimator:

Residuals: $u = y = x\hat{\beta}$
Estimator *coming from the residuals*: $\hat{b} = (X'X)^{-1} X'u$

After inserting $u$ in $\hat{b}$ the base formula results:
$\hat{\beta}^{t}= \hat{\beta}^{t-1} + v(\hat{\beta} - \hat{\beta}^{t-1})$

I am unsure, if the first term inside parenthesis is just $\hat{\beta}$ or rather $\hat{\beta}^{something}$. Please check. 


